// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFYSSSQ_FJaHV8-E6-LMZf-nU2R6DOGhw',
    appId: '1:751107980777:web:99b10589c25eabcb6adf78',
    messagingSenderId: '751107980777',
    projectId: 'gusto-meet',
    authDomain: 'gusto-meet.firebaseapp.com',
    storageBucket: 'gusto-meet.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASv6lwNoJSVydCeSFYeVcsxpFJBYBn8Qk',
    appId: '1:751107980777:android:eeafc25eec0be8b26adf78',
    messagingSenderId: '751107980777',
    projectId: 'gusto-meet',
    storageBucket: 'gusto-meet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASv6lwNoJSVydCeSFYeVcsxpFJBYBn8Qk',
    appId: '1:751107980777:ios:someplaceholder',
    messagingSenderId: '751107980777',
    projectId: 'gusto-meet',
    storageBucket: 'gusto-meet.firebasestorage.app',
    iosBundleId: 'com.carevo.gustomeets',
  );
}
